name: workflow-2

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/workflow-2.yml

jobs:
  workflow_2:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow 2
        shell: bash
        run: |
          sleep 45
          date
