name: workflow-1

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/workflow-1.yml

jobs:
  workflow_1:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow 1
        shell: bash
        run: |
          sleep 15
          date
